/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    articles: Article;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  /**
   * URL slug for /projects/[slug]. Auto-generated from name if left empty.
   */
  slug?: string | null;
  /**
   * One-line outcome shown on the homepage and project list.
   */
  proof?: string | null;
  /**
   * What problem did this solve?
   */
  problem?: string | null;
  /**
   * What you owned on this project.
   */
  role?: string | null;
  /**
   * Measurable or concrete result.
   */
  outcome?: string | null;
  /**
   * What you chose (and why) — state, data fetching, architecture, etc.
   */
  decisions?: string | null;
  /**
   * Short proof points (e.g. Monthly users / 1M+). Prefer real numbers.
   */
  metrics?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional longer context. Prefer problem / role / outcome above.
   */
  desc?: string | null;
  action: string;
  uri: string;
  image?: (number | null) | Media;
  /**
   * Optional override. If empty, a live screenshot is generated from the project Live URL.
   */
  imageUrl?: string | null;
  /**
   * Overrides proof for Open Graph and meta description when set.
   */
  seoDescription?: string | null;
  technologies: {
    name: string;
    id?: string | null;
  }[];
  /**
   * Lower numbers appear first
   */
  order: number;
  /**
   * Show on the home page featured section
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  kind: 'external' | 'full';
  slug?: string | null;
  externalUrl?: string | null;
  publishedAt: string;
  readTime: string;
  summary?: string | null;
  categories?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  /**
   * Used when no uploaded image is set (e.g. Hashnode/Medium CDN)
   */
  imageUrl?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Lower numbers appear first
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  proof?: T;
  problem?: T;
  role?: T;
  outcome?: T;
  decisions?: T;
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  desc?: T;
  action?: T;
  uri?: T;
  image?: T;
  imageUrl?: T;
  seoDescription?: T;
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  slug?: T;
  externalUrl?: T;
  publishedAt?: T;
  readTime?: T;
  summary?: T;
  categories?:
    | T
    | {
        name?: T;
        id?: T;
      };
  image?: T;
  imageUrl?: T;
  content?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Homepage intro under your name.
   */
  about?: {
    role?: string | null;
    title?: string | null;
    /**
     * First paragraph. Highlighted terms below are emphasized automatically.
     */
    intro?: string | null;
    /**
     * Second paragraph. Add links with [[label|/path]], e.g. [[write|/articles]].
     */
    body?: string | null;
    /**
     * Words or phrases to emphasize in the intro paragraph.
     */
    highlights?:
      | {
          term: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * WhatsApp and other direct contact options.
   */
  contact?: {
    /**
     * Digits only with country code (no + or spaces). Example: 2348012345678.
     */
    whatsappPhone?: string | null;
    /**
     * Prefill message when someone opens WhatsApp.
     */
    whatsappMessage?: string | null;
  };
  /**
   * Selective roles shown on the homepage (impact over job history).
   */
  experience?:
    | {
        company: string;
        role: string;
        /**
         * Optional chip next to the role (e.g. Promoted to Team Lead).
         */
        badge?: string | null;
        /**
         * e.g. 2023 — Present
         */
        period?: string | null;
        /**
         * One-line scope for the role.
         */
        summary?: string | null;
        highlights?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  navLinks?:
    | {
        name: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        name: string;
        uri: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Copyright line. Year is generated automatically from the current date.
   */
  footer?: {
    /**
     * Shown as © {year} NAME
     */
    copyrightName?: string | null;
    location?: string | null;
    /**
     * IANA timezone (e.g. Africa/Lagos). Offset is computed live as UTC±X — not stored as a fixed string.
     */
    timezone?: string | null;
  };
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              isEmail?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  about?:
    | T
    | {
        role?: T;
        title?: T;
        intro?: T;
        body?: T;
        highlights?:
          | T
          | {
              term?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        whatsappPhone?: T;
        whatsappMessage?: T;
      };
  experience?:
    | T
    | {
        company?: T;
        role?: T;
        badge?: T;
        period?: T;
        summary?: T;
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  navLinks?:
    | T
    | {
        name?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        name?: T;
        uri?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        copyrightName?: T;
        location?: T;
        timezone?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              isEmail?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}